### ISSUE TITLE
What are the aspects of OGC API Tiles do you would like to experiment with?

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/OGC-OS-Sprint-04-2020#3]
These are some ideas. Propose new ones, elaborate or vote for the most urgent

* Vector tiles remaining questions
* Tiles created from maps adding styles
  - map\{styleId}\tile\{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}.png
* Tiles in Tile Matrix Sets 
  - other than WebMercatorQuad
  - other than "Quad" (no powers of 2 zoom levels)
* Services combining some resources retrievable as tiles and some that are not
* Tiles that has no known source (or the source cannot be retrieved)
* Tiles created from more than one resource
  - How to link to sources
  - Flexibility level
    - Predefined combinations of sources
    - Free combination of sources (cache and performance issues)

**Comment by ghobona** [comment]
Please also complete the questionnaire at https://docs.google.com/forms/d/1_PwM5eUuhuMB7yCxuHVWZ660VE7Alti4QM7VR6CUlDE

**Comment by jeffharrison** [comment]
It would be interesting to see if Mapbox vector tiles could be accessed from these OGC API - Tiles implementations... 

http://maps.ecere.com/geoapi/

https://services.interactive-instruments.de/t15/daraa

https://vtp2.geo-solutions.it/geoserver/ogc/features

https://ogc-vtp.gospatial.org/ogc-api-tiles

They were deployed for the OGC Vector Tiles Pilot.

Best Regards,
Jeff

**Comment by notthatbreezy** [comment]
A few things that we (Azavea) will be exploring during the sprint is how well OGC - API Tiles interacts with the STAC specification (a subset of OGC - API Features). We will be exploring options for implementation with [Franklin](https://azavea.github.io/franklin/), an open source STAC server.

Specifically - we will be looking to answer the following questions:
 - Is it possible to add raster tile rendering for STAC items (OGC Features)?
 - How should we render both raster and vector tiles for collections that have thousands or hundreds or thousands of items in the collection?
 - What is the best way to leverage tiles for rendered views of a STAC API in a browser?

**Comment by jerstlouis** [comment]
What we are experimenting with for the Tiles API code sprint at Ecere is how tiles could be leveraged, together with a process invocation description document, to do chained distributed processing (including considering rendering a map on the server as a type of process, where each data layer being rendered is an input which can have parameters e.g. styling information).

This is in line with what we proposed at the Coverage & Analytics sprint as a simple JSON encoding to describe inputs and parameters:
    https://gist.github.com/jerstlouis/fa274c97df26537164e60edda9500585
    https://gist.github.com/jerstlouis/567acb48537a748ee9bee6f9659fcc1c

@notthatbreezy a specific use case of that was that an input to a server-side (tiled or not) rendering process could be a STAC API with parameters.

**Comment by ghobona** [comment]
Great job everyone!

**Comment by jeffharrison** [comment]
Just testing a post of these links before potentially putting them over on Common Issues. Pls ignore ...

http://maps.ecere.com/geoapi/

https://services.interactive-instruments.de/t15/daraa

https://vtp2.geo-solutions.it/geoserver/ogc/features

https://ogc-vtp.gospatial.org/ogc-api-tiles
